name: build_host
on:
  push:
    branches:
      - master
    paths:
      - packages/home_camper_host/**

permissions:
  contents: write
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          cache: true

      - name: Set up key.properties
        run: |
          echo "keyPassword=${{ secrets.KEY_PASSWORD_HOST }}" > packages/home_camper_host/android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_HOST }}" >> packages/home_camper_host/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_HOST }}" >> packages/home_camper_host/android/key.properties
          echo "${{ secrets.STORE_FILE_CONTENTS_HOST }}" | base64 --decode > packages/home_camper_host/android/key.jks

      - name: Set up local.properties
        run: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Set up Play Store Secret
        run: |
          echo "${{ secrets.PLAY_STORE_SECRET }}" | base64 --decode > android/play_store_secret.json

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          rubygems: latest

      - name: Increment version and deploy
        run: |
          cd packages/home_camper_host/android && bundle install && bundle exec fastlane increment_version && bundle exec fastlane deploy_closed
          cd ../../..
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version increase
          file_pattern: "*.gradle *.xml"
